// Options for TryOnV2Beta components based on PhotoShoot_Studio JSON files

export const footwearOptions = {
  male: {
    traditional: [
      "kolhapuri chappals",
      "mojris",
      "juttis",
      "ethnic sandals",
      "traditional slippers",
      "leather sandals",
      "fisherman sandals",
      "rajasthani juttis",
      "embroidered mojris",
      "pathani sandals",
      "punjabi juttis",
      "royal mojris",
      "wedding juttis",
      "festive sandals",
      "ethnic flats"
    ],
    casual: [
      "sneakers",
      "running shoes",
      "walking shoes",
      "training shoes",
      "canvas shoes",
      "slip-on sneakers",
      "high-top sneakers",
      "low-top sneakers",
      "skate shoes",
      "trail shoes",
      "boat shoes",
      "espadrilles",
      "casual loafers",
      "flip flops",
      "thong sandals",
      "sport sandals",
      "crocs",
      "clogs",
      "sliders",
      "slip-on shoes",
      "mesh sneakers",
      "knit sneakers",
      "lightweight trainers",
      "gym shoes",
      "travel sneakers",
      "road shoes",
      "urban sneakers",
      "daily wear sandals",
      "comfort sandals"
    ],
    formal: [
      "formal leather shoes",
      "oxford shoes",
      "derby shoes",
      "brogues",
      "monk strap shoes",
      "loafers",
      "tassel loafers",
      "penny loafers",
      "moccasins",
      "driving shoes",
      "office loafers",
      "party shoes",
      "lace-up formal shoes",
      "slip-on formal shoes",
      "velvet loafers",
      "patent leather shoes",
      "suede loafers",
      "formal boots",
      "lace-up boots",
      "zip boots",
      "suede boots",
      "leather boots",
      "dress boots",
      "ankle formal boots",
      "chelsea formal boots",
      "business shoes",
      "corporate shoes",
      "wedding shoes"
    ],
    fashion: [
      "chunky sneakers",
      "platform sneakers",
      "designer sneakers",
      "metallic sneakers",
      "neon sneakers",
      "printed sneakers",
      "color block sneakers",
      "runway shoes",
      "transparent shoes",
      "studded loafers",
      "velvet slip-ons",
      "embellished loafers",
      "futuristic sneakers",
      "techwear boots",
      "combat fashion boots",
      "biker boots",
      "riding boots",
      "cowboy boots",
      "street style sneakers",
      "luxury sneakers",
      "limited edition sneakers",
      "celebrity style shoes",
      "party boots",
      "high shine shoes",
      "mirror finish shoes",
      "gold finish shoes",
      "silver finish shoes"
    ]
  },
  female: {
    traditional: [
      "kolhapuri chappals",
      "mojris",
      "juttis",
      "embroidered juttis",
      "beaded sandals",
      "mirror-work sandals",
      "traditional slippers",
      "festive sandals",
      "wedding juttis",
      "ethnic sandals",
      "ethnic heels",
      "bridal sandals",
      "temple sandals",
      "zardozi juttis",
      "kundan sandals",
      "heritage mojris",
      "rajasthani juttis",
      "royal juttis"
    ],
    casual: [
      "sneakers",
      "running shoes",
      "walking shoes",
      "training shoes",
      "slip-on sneakers",
      "canvas shoes",
      "fashion sneakers",
      "platform sneakers",
      "chunky sneakers",
      "high-top sneakers",
      "ballet flats",
      "pointed-toe flats",
      "square-toe flats",
      "slingback flats",
      "peep-toe flats",
      "dorsay flats",
      "ankle strap flats",
      "lace-up flats",
      "embellished flats",
      "knit flats",
      "gladiator sandals",
      "strappy sandals",
      "slide sandals",
      "flip flops",
      "thong sandals",
      "sport sandals",
      "platform sandals",
      "wedge sandals",
      "comfort sandals",
      "daily wear flats",
      "travel sandals",
      "crocs",
      "clogs",
      "sliders"
    ],
    formal: [
      "kitten heels",
      "block heels",
      "stiletto heels",
      "wedge heels",
      "platform heels",
      "cone heels",
      "spool heels",
      "cork heels",
      "lucite heels",
      "sculpted heels",
      "pumps",
      "court shoes",
      "ankle strap heels",
      "mule heels",
      "slingback heels",
      "peep-toe heels",
      "open-toe heels",
      "closed-toe heels",
      "party heels",
      "bridal heels",
      "office heels",
      "formal sandals",
      "corporate heels",
      "wedding heels"
    ],
    fashion: [
      "metallic heels",
      "neon heels",
      "transparent heels",
      "designer heels",
      "runway heels",
      "furry sandals",
      "feather heels",
      "embellished heels",
      "stud sandals",
      "glitter heels",
      "crystal heels",
      "mirror heels",
      "lace heels",
      "velvet heels",
      "platform boots",
      "fashion boots",
      "knee-high boots",
      "over-the-knee boots",
      "cowboy boots",
      "chunky boots",
      "combat fashion boots",
      "street style sneakers",
      "luxury sneakers",
      "celebrity heels",
      "statement heels",
      "party boots",
      "high shine heels"
    ]
  }
}

export const backgroundOptions = {
  studio_backgrounds: [
    "plain white studio",
    "light grey studio",
    "beige studio",
    "cream studio",
    "off-white studio",
    "pastel pink studio",
    "pastel blue studio",
    "pastel green studio",
    "matte black studio",
    "charcoal grey studio",
    "textured concrete wall",
    "subtle marble wall",
    "light wooden panel wall",
    "dark wooden panel wall",
    "brick wall studio",
    "white brick wall",
    "fabric drape backdrop",
    "linen curtain backdrop",
    "sheer white curtain backdrop",
    "soft gradient backdrop",
    "neutral wallpaper",
    "muted floral wallpaper",
    "minimal patterned wallpaper",
    "hand-painted studio wall",
    "subtle geometric wall"
  ],
  luxury_interiors: [
    "luxury hotel lobby",
    "modern hotel corridor",
    "boutique hotel interior",
    "hotel suite interior",
    "marble hallway",
    "designer showroom",
    "fashion studio interior",
    "high-end shopping mall",
    "luxury penthouse interior",
    "modern apartment living room",
    "stylish cafe interior",
    "fine dining restaurant",
    "executive lounge",
    "business class lobby",
    "art deco interior",
    "glass atrium lobby",
    "royal banquet hall",
    "heritage hotel interior",
    "antique mansion interior",
    "luxury villa interior",
    "private club interior",
    "premium spa interior",
    "crystal chandelier hall",
    "gold accented hallway",
    "velvet lounge interior"
  ],
  office_corporate: [
    "corporate office lobby",
    "office corridor",
    "conference room",
    "glass building interior",
    "co-working space",
    "startup office interior",
    "business lounge",
    "executive office",
    "boardroom interior",
    "corporate reception area",
    "training room",
    "seminar hall",
    "IT office workspace",
    "open plan office",
    "corner office",
    "office cafeteria",
    "corporate hallway",
    "office waiting area",
    "management cabin",
    "strategy room",
    "presentation room",
    "innovation lab",
    "design studio office",
    "tech hub interior",
    "corporate library"
  ],
  urban_outdoor: [
    "urban street",
    "city sidewalk",
    "business district street",
    "pedestrian street",
    "brick wall street",
    "art district street",
    "market street",
    "heritage street",
    "residential street",
    "old town lane",
    "city square",
    "metro station exterior",
    "subway entrance",
    "bus stop street",
    "crosswalk street",
    "bridge walkway",
    "riverfront promenade",
    "lakeside promenade",
    "harbor walkway",
    "boardwalk street",
    "skyscraper plaza",
    "downtown crossing",
    "urban park entrance",
    "shopping street",
    "street cafe exterior"
  ],
  nature_garden: [
    "garden pathway",
    "park lawn",
    "flower garden",
    "courtyard with plants",
    "villa garden",
    "hotel garden",
    "resort garden",
    "heritage courtyard",
    "palace garden",
    "sunlit lawn",
    "botanical garden",
    "greenhouse garden",
    "terrace garden",
    "balcony garden",
    "courtyard fountain",
    "palm tree walkway",
    "rose garden",
    "tropical garden",
    "zen garden",
    "forest garden",
    "riverbank greenery",
    "lake garden",
    "hill garden",
    "sunset garden",
    "misty garden"
  ],
  beach_resort: [
    "beach resort walkway",
    "poolside resort",
    "wooden deck",
    "seaside cafe",
    "sunset beach",
    "outdoor patio",
    "rooftop terrace",
    "balcony city view",
    "hill resort balcony",
    "tropical beach resort",
    "cliffside terrace",
    "lake house exterior",
    "riverbank walkway",
    "waterfront deck",
    "marina boardwalk",
    "beach boardwalk",
    "coastal road",
    "island resort path",
    "seaside villa terrace",
    "sunrise beach",
    "beach lounge",
    "palm beach walkway",
    "ocean view balcony",
    "shoreline path",
    "beach cabana"
  ]
}

export const accessoryOptions = {
  male: {
    traditional: [
      "safa",
      "pagdi",
      "turban pin",
      "kurta brooch",
      "sherwani brooch",
      "angavastram",
      "rudraksha mala",
      "gold chain",
      "silver chain",
      "kada",
      "ethnic stole",
      "shawl",
      "muffler",
      "khadi scarf",
      "traditional waistband"
    ],
    fashion_theme: [
      "sunglasses",
      "aviator sunglasses",
      "wayfarer sunglasses",
      "sports sunglasses",
      "round glasses",
      "square glasses",
      "smart glasses",
      "luxury watch",
      "chronograph watch",
      "digital watch",
      "sports watch",
      "leather strap watch",
      "metal strap watch",
      "bracelet watch",
      "tie",
      "bow tie",
      "cravat",
      "pocket square",
      "lapel pin",
      "cufflinks",
      "fedora hat",
      "panama hat",
      "cowboy hat",
      "bucket hat",
      "snapback cap",
      "beanie",
      "bandana",
      "neck gaiter",
      "wallet chain",
      "fabric belt",
      "braided belt",
      "designer belt"
    ],
    other_utility: [
      "wallet",
      "leather wallet",
      "card holder",
      "money clip",
      "passport holder",
      "travel wallet",
      "key holder",
      "keychain",
      "ID card holder",
      "backpack",
      "laptop bag",
      "messenger bag",
      "sling bag",
      "crossbody bag",
      "travel bag",
      "gym bag",
      "duffel bag",
      "briefcase",
      "smartwatch",
      "fitness band",
      "earphones case",
      "phone pouch",
      "power bank pouch",
      "rain cap",
      "winter gloves",
      "cycling gloves"
    ]
  },
  female: {
    traditional: [
      "jhumkas",
      "kundan necklace",
      "polki necklace",
      "mangalsutra",
      "maang tikka",
      "nath",
      "nose pin",
      "bindi",
      "bangles",
      "gold bangles",
      "silver anklet",
      "toe ring",
      "payal",
      "kamarbandh",
      "ethnic dupatta",
      "odhani",
      "lehenga belt",
      "temple jewelry",
      "meena work necklace",
      "heritage brooch"
    ],
    fashion_theme: [
      "oversized sunglasses",
      "cat eye sunglasses",
      "round sunglasses",
      "square sunglasses",
      "fashion glasses",
      "statement necklace",
      "layered necklace",
      "choker necklace",
      "pendant necklace",
      "bracelet",
      "charm bracelet",
      "tennis bracelet",
      "cuff bracelet",
      "cocktail ring",
      "fashion ring",
      "stackable rings",
      "hair clip",
      "hair pin",
      "hair band",
      "headband",
      "scrunchie",
      "ear cuffs",
      "clip-on earrings",
      "pearl earrings",
      "diamond earrings",
      "silk scarf",
      "printed scarf",
      "stole",
      "shawl",
      "neck scarf"
    ],
    other_utility: [
      "handbag",
      "tote bag",
      "sling bag",
      "clutch bag",
      "crossbody bag",
      "backpack",
      "satchel bag",
      "hobo bag",
      "bucket bag",
      "evening bag",
      "wallet pouch",
      "cosmetic pouch",
      "phone sling",
      "watch",
      "bracelet watch",
      "smartwatch",
      "fitness band",
      "luxury watch",
      "rose gold watch",
      "leather strap watch",
      "metal strap watch",
      "fashion watch",
      "travel scarf",
      "sun hat",
      "winter cap",
      "gloves"
    ]
  }
}

export const jewelryOptions = {
  female: {
    traditional: [
      "jhumkas",
      "kundan necklace",
      "polki necklace",
      "mangalsutra",
      "maang tikka",
      "nath",
      "nose pin",
      "bindi",
      "gold bangles",
      "silver anklet",
      "toe ring",
      "payal",
      "kamarbandh",
      "temple jewelry",
      "meena work necklace",
      "heritage brooch",
      "traditional earrings",
      "ethnic jewelry set"
    ],
    casual: [
      "stud earrings",
      "small hoops",
      "simple necklace",
      "pendant necklace",
      "beaded necklace",
      "thread bracelet",
      "silver bracelet",
      "daily wear ring",
      "minimal necklace",
      "chain necklace",
      "small nose pin",
      "anklet",
      "hair pin",
      "simple bangle",
      "oxidized jewelry",
      "casual earrings",
      "simple mangalsutra"
    ],
    formal: [
      "diamond earrings",
      "pearl earrings",
      "tennis bracelet",
      "cocktail ring",
      "statement necklace",
      "layered necklace",
      "choker necklace",
      "gold necklace",
      "platinum ring",
      "office wear earrings",
      "formal necklace",
      "formal bracelet",
      "formal ring",
      "formal jewelry set",
      "luxury jewelry set"
    ],
    fashion: [
      "ear cuffs",
      "clip-on earrings",
      "stackable rings",
      "fashion ring",
      "boho necklace",
      "chunky necklace",
      "oversized earrings",
      "colorful bangles",
      "shell necklace",
      "mirror work jewelry",
      "resin jewelry",
      "acrylic jewelry",
      "geometric earrings",
      "asymmetric earrings",
      "celebrity style jewelry",
      "runway jewelry",
      "statement earrings",
      "trendy choker"
    ],
    bridal_full_set: [
      "bridal jewelry set",
      "kundan bridal set",
      "polki bridal set",
      "temple bridal set",
      "diamond bridal set",
      "gold bridal set",
      "heritage bridal set",
      "rajputi bridal set",
      "south indian bridal set",
      "bengali bridal set",
      "maharashtrian bridal set",
      "punjabi bridal set",
      "bridal choker",
      "bridal long necklace",
      "bridal layered necklace",
      "bridal rani haar",
      "bridal haaram",
      "bridal mangalsutra",
      "maang tikka",
      "matha patti",
      "passa",
      "nath",
      "nose chain",
      "bridal jhumkas",
      "bridal chandbalis",
      "bridal studs",
      "bridal bangles",
      "chooda",
      "kada bangles",
      "bridal bracelet",
      "kamarbandh",
      "armlet (bajuband)",
      "hand harness (haath phool)",
      "toe rings",
      "payal (anklets)",
      "bridal bindi",
      "hair jewelry",
      "juda pin",
      "hair chain",
      "full bridal jewelry look",
      "complete bridal jewelry set",
      "head to toe bridal jewelry"
    ]
  },
  male: {
    traditional: [
      "rudraksha mala",
      "gold chain",
      "silver chain",
      "kada",
      "sherwani brooch",
      "turban pin",
      "ethnic necklace",
      "temple chain",
      "traditional ring"
    ],
    casual: [
      "chain necklace",
      "simple ring",
      "silver ring",
      "bracelet",
      "beaded bracelet",
      "leather bracelet",
      "thread bracelet",
      "daily wear ring",
      "minimal pendant",
      "casual chain"
    ],
    formal: [
      "gold ring",
      "platinum ring",
      "signet ring",
      "formal bracelet",
      "formal chain",
      "office wear ring",
      "luxury bracelet",
      "formal pendant"
    ],
    fashion: [
      "skull ring",
      "statement ring",
      "chunky chain",
      "layered chain",
      "dog tag necklace",
      "cross pendant",
      "locket",
      "stud earring",
      "ear hoop",
      "nose stud",
      "piercing ring",
      "street style chain",
      "celebrity style chain",
      "runway ring",
      "futuristic jewelry"
    ]
  }
}


// Grouped options getters for categorization
export const getGroupedFootwearOptions = (gender: string) => {
  const genderKey = gender === "male" ? "male" : "female"
  return footwearOptions[genderKey as keyof typeof footwearOptions]
}

export const getGroupedBackgroundOptions = () => {
  return backgroundOptions
}

export const getGroupedAccessoryOptions = (gender: string) => {
  const genderKey = gender === "male" ? "male" : "female"
  return accessoryOptions[genderKey as keyof typeof accessoryOptions]
}

export const getGroupedJewelryOptions = (gender: string) => {
  const genderKey = gender === "male" ? "male" : "female"
  return jewelryOptions[genderKey as keyof typeof jewelryOptions]
}
