export const MODEL_FACE_RETURN_URL_KEY = "ai4fi:modelFace:returnUrl"
export const DRESS_IMAGE_PERSIST_KEY = "ai4fi:tryon:persistedDressImage"
export const PRODUCT_LISTING_PERSIST_KEY = "ai4fi:productListing:persistedData"
export const FABRIC_STUDIO_PERSIST_KEY = "ai4fi:fabricStudio:persistedData"
export const TRIAL_ROOM_HANDOFF_KEY = "ai4fi:trialRoom:handoff"
