export const nationalityOptions = [
  { value: "Indian", label: "Indian" },
  { value: "American", label: "American" },
  { value: "British", label: "British" },
  { value: "Canadian", label: "Canadian" },
  { value: "Australian", label: "Australian" },
  { value: "French", label: "French" },
  { value: "Italian", label: "Italian" },
  { value: "German", label: "German" },
  { value: "Spanish", label: "Spanish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Argentinian", label: "Argentinian" },
  { value: "Colombian", label: "Colombian" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "Arab (Middle Eastern)", label: "Arab (Middle Eastern)" },
  { value: "Saudi", label: "Saudi" },
  { value: "Emirati", label: "Emirati" },
  { value: "Turkish", label: "Turkish" },
  { value: "Iranian", label: "Iranian" },
  { value: "Chinese", label: "Chinese" },
  { value: "Japanese", label: "Japanese" },
  { value: "Korean", label: "Korean" },
  { value: "Thai", label: "Thai" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Filipino", label: "Filipino" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "African", label: "African" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "South African", label: "South African" },
  { value: "Russian", label: "Russian" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Mixed Nationality", label: "Mixed Nationality" },
];

// Keep for backward compatibility
export const countryOptions = nationalityOptions;

export const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
];

export const modeOptions = [
  { value: "face", label: "Face" },
  { value: "fashion", label: "Fashion" },
];

export const ageRangeOptions = [
  { value: "18-22", label: "18-22" },
  { value: "23-27", label: "23-27" },
  { value: "28-32", label: "28-32" },
  { value: "33-38", label: "33-38" },
  { value: "39-45", label: "39-45" },
  { value: "46-55", label: "46-55" },
];

// Female hair colors
export const femaleHairColorOptions = [
  { value: "Black", label: "Black" },
  { value: "Dark Brown", label: "Dark Brown" },
  { value: "Light Brown", label: "Light Brown" },
  { value: "Chestnut", label: "Chestnut" },
  { value: "Golden Brown", label: "Golden Brown" },
  { value: "Blonde", label: "Blonde" },
  { value: "Auburn", label: "Auburn" },
  { value: "Red", label: "Red" },
  { value: "Grey", label: "Grey" },
  { value: "Salt and Pepper", label: "Salt and Pepper" },
];

// Male hair colors
export const maleHairColorOptions = [
  { value: "Black", label: "Black" },
  { value: "Dark Brown", label: "Dark Brown" },
  { value: "Light Brown", label: "Light Brown" },
  { value: "Brown", label: "Brown" },
  { value: "Blonde", label: "Blonde" },
  { value: "Grey", label: "Grey" },
  { value: "Salt and Pepper", label: "Salt and Pepper" },
  { value: "Bald", label: "Bald" },
];

// Keep for backward compatibility
export const hairColorOptions = femaleHairColorOptions;

// Female hair styles (from JSON)
export const femaleHairStyleOptions = [
  { value: "Straight Open Hair", label: "Straight Open Hair" },
  { value: "Soft Waves", label: "Soft Waves" },
  { value: "Curly Hair", label: "Curly Hair" },
  { value: "Romantic Curly", label: "Romantic Curly" },
  { value: "Long Wavy Hair", label: "Long Wavy Hair" },
  { value: "High Ponytail", label: "High Ponytail" },
  { value: "Low Ponytail", label: "Low Ponytail" },
  { value: "Loose Bun", label: "Loose Bun" },
  { value: "Tight Bun", label: "Tight Bun" },
  { value: "Side Braid", label: "Side Braid" },
  { value: "Center Parted Hair", label: "Center Parted Hair" },
  { value: "Short Bob Cut", label: "Short Bob Cut" },
  { value: "Shoulder Length Hair", label: "Shoulder Length Hair" },
];

// Male hair styles (from JSON)
export const maleHairStyleOptions = [
  { value: "Short Side Cut", label: "Short Side Cut" },
  { value: "Crew Cut", label: "Crew Cut" },
  { value: "Fade Cut", label: "Fade Cut" },
  { value: "Classic Side Part", label: "Classic Side Part" },
  { value: "Slick Back", label: "Slick Back" },
  { value: "Messy Hair", label: "Messy Hair" },
  { value: "Medium Length Hair", label: "Medium Length Hair" },
  { value: "Long Hair", label: "Long Hair" },
  { value: "Man Bun", label: "Man Bun" },
  { value: "Buzz Cut", label: "Buzz Cut" },
  { value: "Clean Shaved Head", label: "Clean Shaved Head" },
];

// Keep for backward compatibility
export const hairTypeOptions = femaleHairStyleOptions;

export const eyeColorOptions = [
  { value: "Dark Brown", label: "Dark Brown" },
  { value: "Brown", label: "Brown" },
  { value: "Light Brown", label: "Light Brown" },
  { value: "Hazel", label: "Hazel" },
  { value: "Green", label: "Green" },
  { value: "Blue", label: "Blue" },
  { value: "Grey", label: "Grey" },
];

export const skinToneOptions = [
  { value: "Very Fair", label: "Very Fair" },
  { value: "Fair", label: "Fair" },
  { value: "Mediun Fair", label: "Medium Fair" },
  { value: "Light Wheatish", label: "Light Wheatish" },
  { value: "Medium Wheatish", label: "Medium Wheatish" },
  { value: "Olive", label: "Olive" },
  { value: "Tan", label: "Tan" },
  { value: "Dusky", label: "Dusky" },
  { value: "Deep Brown", label: "Deep Brown" },
];

// Keep for backward compatibility
export const skinColorOptions = skinToneOptions;

// Mood/Expression options
export const moodOptions = [
  { value: "Confident", label: "Confident" },
  { value: "Soft Smile", label: "Soft Smile" },
  { value: "Elegant", label: "Elegant" },
  { value: "Bold", label: "Bold" },
  { value: "Calm", label: "Calm" },
  { value: "Happy", label: "Happy" },
  { value: "Serious", label: "Serious" },
  { value: "Graceful", label: "Graceful" },
  { value: "Neutral", label: "Neutral" },
  { value: "Strong", label: "Strong" },
  { value: "Friendly Smile", label: "Friendly Smile" },
  { value: "Professional", label: "Professional" },
];

// Beard options (for male face mode)
export const beardOptions = [
  { value: "clean-shaven", label: "Clean Shaven" },
  { value: "stubble", label: "Stubble" },
  { value: "short beard", label: "Short Beard" },
  { value: "medium beard", label: "Medium Beard" },
  { value: "long beard", label: "Long Beard" },
  { value: "goatee", label: "Goatee" },
  { value: "mustache", label: "Mustache" },
];

// Body type options
export const femaleBodyTypeOptions = [
  { value: "Slim", label: "Slim" },
  { value: "Slim Athletic", label: "Slim Athletic" },
  { value: "Curvy", label: "Curvy" },
  { value: "Hourglass", label: "Hourglass" },
  { value: "Pear Shaped", label: "Pear Shaped" },
  { value: "Petite", label: "Petite" },
  { value: "Plus Size", label: "Plus Size" },
  { value: "Tall and Lean", label: "Tall and Lean" },
];

export const maleBodyTypeOptions = [
  { value: "Slim", label: "Slim" },
  { value: "Lean", label: "Lean" },
  { value: "Athletic", label: "Athletic" },
  { value: "Muscular", label: "Muscular" },
  { value: "Broad Shoulders", label: "Broad Shoulders" },
  { value: "Average Build", label: "Average Build" },
  { value: "Heavy Build", label: "Heavy Build" },
  { value: "Tall and Lean", label: "Tall and Lean" },
];

// Pose type options
export const poseTypeOptions = [
  { value: "half", label: "Half Body" },
  { value: "full", label: "Full Body" },
];

// Keep for backward compatibility
export const poseOptions = [
  { value: "Standing Relaxed", label: "Standing Relaxed" },
  { value: "Crossed Arms", label: "Crossed Arms" },
  { value: "Over the Shoulder Look", label: "Over the Shoulder Look" },
  { value: "Hands on Hips", label: "Hands on Hips" },
  { value: "Walking Runway Stance", label: "Walking Runway Stance" },
  { value: "Seated Elegance", label: " Seated Elegance" },
  { value: "Leaning Against Surface", label: " Leaning Against Surface" },
  { value: "Mid-Motion Turn", label: "Mid-Motion Turn" },
  { value: "Hands in Pockets", label: "Hands in Pockets" },
  { value: "Side Profile Pose", label: "Side Profile Pose" },
];

export const backgroundOptions = [
  { value: "Auto", label: "Auto" },
  { value: "Plain White Studio", label: "Plain White Studio" },
  { value: "Soft Beige Gradient", label: "Soft Beige Gradient" },
  { value: "Textured Concrete Wall", label: "Textured Concrete Wall" },
  { value: "Exposed Brick Wall", label: "Exposed Brick Wall" },
  { value: "Wooden Floor with Neutral Wall", label: "Wooden Floor with Neutral Wall" },
  { value: "Large Window with Natural Light", label: "Large Window with Natural Light" },
  { value: "Minimalist Interior Design", label: "Minimalist Interior Design" },
  { value: "Garden Patio", label: "Garden Patio" },
  { value: "City Rooftop Skyline", label: "City Rooftop Skyline" },
  { value: "Luxury Dressing Room", label: "Luxury Dressing Room" },
  { value: "Vintage Library", label: "Vintage Library" },
  { value: "Boutique Storefront", label: "Boutique Storefront" },
  { value: "Cafe Interior", label: "Cafe Interior" },
  { value: "Beachfront Deck", label: "Beachfront Deck" },
  { value: "Floral Meadow", label: "Floral Meadow" },
  { value: "Open Field with Tall Grass", label: "Open Field with Tall Grass" },
  { value: "Industrial Warehouse", label: "Industrial Warehouse" },
  { value: "Urban Street Scene", label: "Urban Street Scene" },
  { value: "Luxury Hotel Suite", label: "Luxury Hotel Suite" },
  { value: "Paved Courtyard", label: "Paved Courtyard" },
  { value: "Artistic Studio with Props", label: "Artistic Studio with Props" },
  { value: "Pastel Color Backdrops", label: "Pastel Color Backdrops" },
  { value: "Neon Cityscape at Night", label: "Neon Cityscape at Night" },
  { value: "Desert Landscape", label: "Desert Landscape" },
  { value: "Tropical Forest", label: "Tropical Forest" },
  { value: "Modern Loft Interior", label: "Modern Loft Interior" },
  { value: "Renaissance Art Museum", label: "Renaissance Art Museum" },
  { value: "Snow-Covered Mountains", label: "Snow-Covered Mountains" },
  { value: "Glass Atrium with Plants", label: "Glass Atrium with Plants" },
  { value: "Contemporary Office Space", label: "Contemporary Office Space" },
];

// Female dress types (from JSON)
export const femaleDressTypeOptions = [
  { value: "Office Suit", label: "Office Suit" },
  { value: "Formal Dress", label: "Formal Dress" },
  { value: "Business Outfit", label: "Business Outfit" },
  { value: "Evening Gown", label: "Evening Gown" },
  { value: "Party Dress", label: "Party Dress" },
  { value: "Cocktail Dress", label: "Cocktail Dress" },
  { value: "Casual Top and Jeans", label: "Casual Top and Jeans" },
  { value: "Casual Dress", label: "Casual Dress" },
  { value: "Summer Dress", label: "Summer Dress" },
  { value: "Traditional Saree", label: "Traditional Saree" },
  { value: "Designer Saree", label: "Designer Saree" },
  { value: "Lehenga Choli", label: "Lehenga Choli" },
  { value: "Anarkali Suit", label: "Anarkali Suit" },
  { value: "Salwar Kameez", label: "Salwar Kameez" },
  { value: "Kurti with Palazzo", label: "Kurti with Palazzo" },
  { value: "Indo-Western Outfit", label: "Indo-Western Outfit" },
  { value: "Middle Eastern Long Dress", label: "Middle Eastern Long Dress" },
  { value: "African Traditional Dress", label: "African Traditional Dress" },
  { value: "Japanese Traditional Kimono", label: "Japanese Traditional Kimono" },
  { value: "Korean Traditional Dress", label: "Korean Traditional Dress" },
  { value: "Chinese Traditional Dress", label: "Chinese Traditional Dress" },
  { value: "Fashion Outfit", label: "Fashion Outfit" },
  { value: "Runway Style Outfit", label: "Runway Style Outfit" },
];

// Male dress types (from JSON)
export const maleDressTypeOptions = [
  { value: "Formal Suit", label: "Formal Suit" },
  { value: "Business Suit", label: "Business Suit" },
  { value: "Three-Piece Suit", label: "Three-Piece Suit" },
  { value: "Tuxedo", label: "Tuxedo" },
  { value: "Blazer with Shirt", label: "Blazer with Shirt" },
  { value: "Blazer with T-Shirt", label: "Blazer with T-Shirt" },
  { value: "Formal Shirt and Trousers", label: "Formal Shirt and Trousers" },
  { value: "Casual Shirt and Jeans", label: "Casual Shirt and Jeans" },
  { value: "T-Shirt and Jeans", label: "T-Shirt and Jeans" },
  { value: "Kurta Pajama", label: "Kurta Pajama" },
  { value: "Kurta with Jacket", label: "Kurta with Jacket" },
  { value: "Sherwani", label: "Sherwani" },
  { value: "Nehru Jacket", label: "Nehru Jacket" },
  { value: "Traditional Ethnic Wear", label: "Traditional Ethnic Wear" },
  { value: "Indo-Western Outfit", label: "Indo-Western Outfit" },
  { value: "Middle Eastern Thobe", label: "Middle Eastern Thobe" },
  { value: "Arab Kandura", label: "Arab Kandura" },
  { value: "African Traditional Wear", label: "African Traditional Wear" },
  { value: "Japanese Traditional Kimono", label: "Japanese Traditional Kimono" },
  { value: "Korean Traditional Hanbok", label: "Korean Traditional Hanbok" },
  { value: "Chinese Traditional Outfit", label: "Chinese Traditional Outfit" },
  { value: "Smart Casual Wear", label: "Smart Casual Wear" },
  { value: "Business Casual Wear", label: "Business Casual Wear" },
  { value: "Luxury Designer Wear", label: "Luxury Designer Wear" },
  { value: "Runway Fashion Outfit", label: "Runway Fashion Outfit" },
  { value: "Western Formal Wear", label: "Western Formal Wear" },
];

// Female footwear options (from JSON)
export const femaleFootwearOptions = [
  { value: "Flat Sandals", label: "Flat Sandals" },
  { value: "Casual Sandals", label: "Casual Sandals" },
  { value: "Office Heels", label: "Office Heels" },
  { value: "Block Heels", label: "Block Heels" },
  { value: "High Heels", label: "High Heels" },
  { value: "Party Heels", label: "Party Heels" },
  { value: "Wedding Heels", label: "Wedding Heels" },
  { value: "Ballet Flats", label: "Ballet Flats" },
  { value: "Office Flats", label: "Office Flats" },
  { value: "Casual Shoes", label: "Casual Shoes" },
  { value: "White Sneakers", label: "White Sneakers" },
  { value: "Sports Shoes", label: "Sports Shoes" },
  { value: "Traditional Indian Sandals", label: "Traditional Indian Sandals" },
  { value: "Traditional Indian Heels", label: "Traditional Indian Heels" },
  { value: "Middle Eastern Sandals", label: "Middle Eastern Sandals" },
  { value: "African Traditional Footwear", label: "African Traditional Footwear" },
  { value: "Fashion Footwear", label: "Fashion Footwear" },
  { value: "Barefoot", label: "Barefoot" },
];

// Male footwear options (from JSON)
export const maleFootwearOptions = [
  { value: "Formal Black Shoes", label: "Formal Black Shoes" },
  { value: "Formal Brown Shoes", label: "Formal Brown Shoes" },
  { value: "Office Shoes", label: "Office Shoes" },
  { value: "Slip-On Shoes", label: "Slip-On Shoes" },
  { value: "Casual Leather Shoes", label: "Casual Leather Shoes" },
  { value: "Sports Shoes", label: "Sports Shoes" },
  { value: "Casual Sneakers", label: "Casual Sneakers" },
  { value: "White Sneakers", label: "White Sneakers" },
  { value: "Boots", label: "Boots" },
  { value: "Ankle Boots", label: "Ankle Boots" },
  { value: "Traditional Indian Shoes (Mojris)", label: "Traditional Indian Shoes (Mojris)" },
  { value: "Nagra sandal", label: "Nagra sandal" },
  { value: "Traditional Leather Sandals", label: "Traditional Leather Sandals" },
  { value: "Middle Eastern Sandals", label: "Middle Eastern Sandals" },
  { value: "African Traditional Shoes", label: "African Traditional Shoes" },
  { value: "Simple Flat Shoes", label: "Simple Flat Shoes" },
  { value: "Fashion Shoes", label: "Fashion Shoes" },
  { value: "Barefoot", label: "Barefoot" },
];

// Tier options
export const tierOptions = [
  { value: "basic", label: "Basic" },
  { value: "professional", label: "Professional" },
];

// Aspect ratio options
export const aspectRatioOptions = [
  { value: "1:1", label: "1:1 (Square)" },
  { value: "2:3", label: "2:3 (Portrait)" },
  { value: "16:9", label: "16:9 (Widescreen)" },
  { value: "9:16", label: "9:16 (Vertical)" },
];

// Resolution options
export const resolutionOptions = [
  { value: "1K", label: "1K" },
  { value: "2K", label: "2K" },
  { value: "4K", label: "4K" },
];

export const fastGenFemalePoses = [
  { value: "divider", label: "Front Poses" },
  { value: "Straight-On, Arms Relaxed", label: "Straight-On, Arms Relaxed (Neutral and clean)" },
  { value: "Hands on Hips", label: "Hands on Hips (Showcase garment fit)" },
  { value: "Crossed Arms", label: "Crossed Arms (Confident, structured look)" },
  { value: "Arms Down, Slight Lean Forward", label: "Arms Down, Slight Lean Forward (Focus on fabric and posture)" },
  { value: "One Hand on Waist, One Arm Relaxed", label: "One Hand on Waist, One Arm Relaxed (Gently angled pose)" },
  { value: "Soft Smile, Neutral Hands by Side", label: "Soft Smile, Neutral Hands by Side (Subtle elegance)" },
  { value: "Hands in Pockets", label: "Hands in Pockets (Casual, relaxed vibe)" },
  { value: "Straight-On with One Leg Crossed", label: "Straight-On with One Leg Crossed (Dynamic stance)" },
  { value: "Hands Resting on Thighs", label: "Hands Resting on Thighs (Showcase lower garments like pants or skirts)" },
  { value: "One Arm Across Chest, Other Arm Relaxed", label: "One Arm Across Chest, Other Arm Relaxed (Soft contrast)" },
  { value: "Lifting One Leg Slightly", label: "Lifting One Leg Slightly (Focus on shoes or pants)" },
  { value: "Subtle Hip Shift", label: "Subtle Hip Shift (Slightly relaxed posture to emphasize clothing flow)" },
  { value: "Slight Lean to One Side", label: "Slight Lean to One Side (Elegance with movement)" },
  { value: "Standing with One Foot Forward", label: "Standing with One Foot Forward (Creates depth)" },
  { value: "Arms Hanging, Slight Head Tilt", label: "Arms Hanging, Slight Head Tilt (Casual, soft look)" },
  { value: "Hand in Hair, Head Slightly Turned", label: "Hand in Hair, Head Slightly Turned (Gives a feminine touch)" },
  { value: "Hands on Thighs, Legs Together", label: "Hands on Thighs, Legs Together (Classic fashion model pose)" },
  { value: "Playful Hand on Hat or Glasses", label: "Playful Hand on Hat or Glasses (Stylish accessory highlight)" },
  { value: "Soft Smile with Hands Resting on Waist", label: "Soft Smile with Hands Resting on Waist (Casual elegance)" },
  { value: "Arms Behind Head, Relaxed", label: "Arms Behind Head, Relaxed (For showing dress or top length)" },
  { value: "divider", label: "Side Profile Poses" },
  {
    value: "Straight-On to Side, One Leg Forward",
    label: "Straight-On to Side, One Leg Forward (Lean into the side, perfect for dresses)",
  },
  { value: "Profile with Hand on Waist", label: "Profile with Hand on Waist (Emphasize silhouette)" },
  { value: "Profile with Arms Crossed", label: "Profile with Arms Crossed (Structured and confident)" },
  { value: "Hand on Hip, Look Over Shoulder", label: "Hand on Hip, Look Over Shoulder (Creates depth and shape)" },
  { value: "Side Lean with One Foot Forward", label: "Side Lean with One Foot Forward (Creates lines in pants/skirts)" },
  { value: "One Hand in Hair, Looking Over Shoulder", label: "One Hand in Hair, Looking Over Shoulder (Feminine, soft look)" },
  { value: "Body Slightly Tilted, Head Facing Forward", label: "Body Slightly Tilted, Head Facing Forward (Emphasizes garment details)" },
  { value: "Hand on Neck, Head Slightly Tilted", label: "Hand on Neck, Head Slightly Tilted (Creates graceful posture)" },
  { value: "Lean Back, Hands on Lower Back", label: "Lean Back, Hands on Lower Back (Bold, strong silhouette)" },
  { value: "Leg Crossed Over the Other", label: "Leg Crossed Over the Other (Gives posture and emphasizes dress length)" },
  { value: "One Arm Raised Over Head, Looking Away", label: "One Arm Raised Over Head, Looking Away (Power pose)" },
  { value: "Profile, One Leg Forward with Arm in Pocket", label: "Profile, One Leg Forward with Arm in Pocket (Casual chic look)" },
  { value: "Crossed Arms with Slight Head Tilt", label: "Crossed Arms with Slight Head Tilt (Relaxed, confident stance)" },
  { value: "Full Side, Both Hands Relaxed by Sides", label: "Full Side, Both Hands Relaxed by Sides (Straightforward, relaxed)" },
  {
    value: "Side Profile, One Arm Resting on Waist, Slight Hip Out",
    label: "Side Profile, One Arm Resting on Waist, Slight Hip Out (Dynamic, bold)",
  },
  { value: "Hands Resting Behind, Looking Over Shoulder", label: "Hands Resting Behind, Looking Over Shoulder (Relaxed yet refined)" },
  { value: "Leaning on Wall or Surface, Looking Forward", label: "Leaning on Wall or Surface, Looking Forward (Casual and stylish)" },
  { value: "Hand Resting on Chest, Head Tilted", label: "Hand Resting on Chest, Head Tilted (Graceful pose)" },
  { value: "One Hand on Hip, Slight Tilt to the Side", label: "One Hand on Hip, Slight Tilt to the Side (Dynamic, accentuating shape)" },
  { value: "Side Profile with Soft Hand on Face", label: "Side Profile with Soft Hand on Face (Subtle elegance)" },

  { value: "divider", label: "Back Poses" },
  { value: "Full Back, Arms Relaxed by Sides", label: "Full Back, Arms Relaxed by Sides (Neutral, minimalist)" },
  { value: "Hands on Hips, Standing Tall", label: "Hands on Hips, Standing Tall (Emphasize back details, like dress/train)" },
  { value: "Back to Camera, Looking Over Shoulder", label: "Back to Camera, Looking Over Shoulder (Adds a soft allure)" },
  { value: "Straight Back, Hands Behind Head", label: "Straight Back, Hands Behind Head (Powerful and structured)" },
  { value: "Arms Behind Back, Head Slightly Tilted", label: "Arms Behind Back, Head Slightly Tilted (Graceful and poised)" },
  { value: "Back View, Arms Resting by Sides", label: "Back View, Arms Resting by Sides (Simple, highlights garment flow)" },
  { value: "Standing Tall with One Foot Slightly Forward", label: "Standing Tall with One Foot Slightly Forward (Creates shape and flow)" },
  { value: "Looking Over Shoulder with Hands Resting Behind", label: "Looking Over Shoulder with Hands Resting Behind (Gentle movement)" },
  { value: "Back View with One Arm Raised", label: "Back View with One Arm Raised (For showing sleeve or shoulder detail)" },
  { value: "Full Back with Hands on Hips", label: "Full Back with Hands on Hips (Bold and powerful posture)" },
];

export const fastGenMalePoses = [
  { value: "divider", label: "Front Poses" },
  { value: "Straight-On, Hands by Sides", label: "Straight-On, Hands by Sides (Clean and neutral)" },
  { value: "Hands in Pockets, Slight Lean", label: "Hands in Pockets, Slight Lean (Casual yet structured)" },
  { value: "Crossed Arms", label: "Crossed Arms (Confident, strong look)" },
  { value: "One Hand on Hip, Other Relaxed", label: "One Hand on Hip, Other Relaxed (Shows fit and silhouette)" },
  { value: "Standing Tall, Shoulders Back", label: "Standing Tall, Shoulders Back (Bold and confident)" },
  { value: "Legs Slightly Apart, Hands in Pockets", label: "Legs Slightly Apart, Hands in Pockets (Relaxed stance)" },
  { value: "Hand on Chest, Slight Head Tilt", label: "Hand on Chest, Slight Head Tilt (Soft, introspective look)" },
  { value: "One Leg Slightly Forward, Hands by Sides", label: "One Leg Slightly Forward, Hands by Sides (Dynamic, flattering angle)" },
  { value: "Arms Relaxed, Slight Lean Forward", label: "Arms Relaxed, Slight Lean Forward (Casual, approachable vibe)" },
  { value: "Straight-On with Slight Hip Out", label: "Straight-On with Slight Hip Out (Casual and confident)" },
  { value: "Hands Resting on Thighs", label: "Hands Resting on Thighs (Showcase lower garment details)" },
  { value: "Relaxed Pose with Slight Hip Shift", label: "Relaxed Pose with Slight Hip Shift (Emphasizes fit and flow)" },
  { value: "One Hand on Shirt Collar, Soft Smile", label: "One Hand on Shirt Collar, Soft Smile (Chic and relaxed)" },
  { value: "One Arm Across Chest, Other Hanging", label: "One Arm Across Chest, Other Hanging (Balanced, relaxed posture)" },
  { value: "One Hand in Hair, Slight Head Tilt", label: "One Hand in Hair, Slight Head Tilt (Stylish, relaxed vibe)" },
  { value: "Lean Forward Slightly, Hands by Sides", label: "Lean Forward Slightly, Hands by Sides (Active and dynamic)" },
  { value: "Hands in Pockets, Slight Lean to One Side", label: "Hands in Pockets, Slight Lean to One Side (Chill yet polished)" },
  { value: "Arms Relaxed, Looking to the Side", label: "Arms Relaxed, Looking to the Side (Slightly neutral but confident)" },
  { value: "Arms Behind Back, Slightly Leaned", label: "Arms Behind Back, Slightly Leaned (Elegant and composed)" },
  { value: "Hands Resting on Thighs, Shoulders Back", label: "Hands Resting on Thighs, Shoulders Back (Strong stance)" },

  { value: "divider", label: "Side Profile Poses" },
  { value: "Full Side, Hands in Pockets", label: "Full Side, Hands in Pockets (Casual, sleek look)" },
  { value: "Side Lean with One Leg Forward", label: "Side Lean with One Leg Forward (Stylized, focus on fit)" },
  { value: "One Arm Across Chest, Other Relaxed", label: "One Arm Across Chest, Other Relaxed (Strong yet balanced)" },
  { value: "Side Profile with Hand in Hair", label: "Side Profile with Hand in Hair (Stylish and youthful)" },
  { value: "Side View, One Foot Forward", label: "Side View, One Foot Forward (Dynamic, emphasizing lines)" },
  { value: "Hand on Neck, Head Tilted", label: "Hand on Neck, Head Tilted (Soft, natural vibe)" },
  { value: "One Hand on Waist, Side Lean", label: "One Hand on Waist, Side Lean (Powerful and confident)" },
  {
    value: "Side Profile, Head Slightly Turned, Looking Forward",
    label: "Side Profile, Head Slightly Turned, Looking Forward (Gives a clean, polished feel)",
  },
  { value: "Relaxed Side, Hands by Sides", label: "Relaxed Side, Hands by Sides (Simple, clean lines)" },
  { value: "One Hand Resting on Pocket, Other Relaxed", label: "One Hand Resting on Pocket, Other Relaxed (Casual and approachable)" },
  {
    value: "Side, Head Slightly Turned with Soft Smile",
    label: "Side, Head Slightly Turned with Soft Smile (Friendly, approachable look)",
  },
  { value: "Hand Resting on Lower Back, Slight Lean", label: "Hand Resting on Lower Back, Slight Lean (Elegant, flowing pose)" },
  { value: "Side Profile with Softly Crossed Arms", label: "Side Profile with Softly Crossed Arms (Structured and calm)" },
  { value: "Legs Crossed at the Ankle, Hands Relaxed", label: "Legs Crossed at the Ankle, Hands Relaxed (Casual and strong)" },
  { value: "Head Facing Forward, Hands Relaxed by Sides", label: "Head Facing Forward, Hands Relaxed by Sides (Neutral, balanced stance)" },
  { value: "Hand Resting on Pocket, Lean Back Slightly", label: "Hand Resting on Pocket, Lean Back Slightly (Relaxed, confident stance)" },
  { value: "One Foot Forward, Arms Behind Back", label: "One Foot Forward, Arms Behind Back (Elegant, structured)" },
  { value: "Relaxed Side, Slightly Arched Back", label: "Relaxed Side, Slightly Arched Back (Creates an appealing silhouette)" },
  { value: "Side Profile with Hands Resting on Waist", label: "Side Profile with Hands Resting on Waist (Strong, confident stance)" },
  { value: "Slight Lean, Looking Off into Distance", label: "Slight Lean, Looking Off into Distance (Contemplative, stylish)" },

  { value: "divider", label: "Back Poses" },
  { value: "Full Back, Arms Relaxed by Sides", label: "Full Back, Arms Relaxed by Sides (Neutral and clean)" },
  { value: "Back to Camera, One Hand on Waist", label: "Back to Camera, One Hand on Waist (Emphasizes body shape)" },
  { value: "Standing Tall with Arms Behind Back", label: "Standing Tall with Arms Behind Back (Strong and composed)" },
  {
    value: "One Leg Slightly Forward, Hands Relaxed by Sides",
    label: "One Leg Slightly Forward, Hands Relaxed by Sides (Dynamic and bold)",
  },
  { value: "Back View, Hands on Lower Back", label: "Back View, Hands on Lower Back (Elegant and poised)" },
  { value: "Back to Camera, Head Over Shoulder", label: "Back to Camera, Head Over Shoulder (Gives a soft yet confident look)" },
  { value: "Full Back with Hands in Pockets", label: "Full Back with Hands in Pockets (Relaxed yet confident)" },
  { value: "Arms Behind Head, Slight Lean", label: "Arms Behind Head, Slight Lean (Powerful, showcasing garment details)" },
  { value: "Back to Camera, One Arm Raised", label: "Back to Camera, One Arm Raised (For showing jacket sleeve or detailing)" },
  {
    value: "Straight Back, One Hand Resting on Collar or Neck",
    label: "Straight Back, One Hand Resting on Collar or Neck (Casual elegance)",
  },
];

export const fastGenFemaleHairStyle = [
  { value: "Sleek Straight Hair", label: "Sleek Straight Hair" },
  { value: "Soft Beach Waves", label: "Soft Beach Waves" },
  { value: "Classic Low Bun", label: "Classic Low Bun" },
  { value: "Center Parted Straight Hair", label: "Center Parted Straight Hair" },
  { value: "Loose Romantic Curls", label: "Loose Romantic Curls" },
  { value: "High Ponytail (sleek)", label: "High Ponytail (sleek)" },
  { value: "Low Ponytail (relaxed)", label: "Low Ponytail (relaxed)" },
  { value: "Side Swept Curls", label: "Side Swept Curls" },
  { value: "Half-Up Half-Down Waves", label: "Half-Up Half-Down Waves" },
  { value: "Voluminous Blowout", label: "Voluminous Blowout" },
  { value: "Slicked Back Wet Look", label: "Slicked Back Wet Look" },
  { value: "Side Part Soft Waves", label: "Side Part Soft Waves" },
  { value: "Messy Bun (clean and elegant)", label: "Messy Bun (clean and elegant)" },
  { value: "Textured Lob (Long Bob)", label: "Textured Lob (Long Bob)" },
  { value: "Soft Layered Cut", label: "Soft Layered Cut" },
  { value: "Straight Lob (Long Bob)", label: "Straight Lob (Long Bob)" },
  { value: "High Top Knot", label: "High Top Knot" },
  { value: "Loose Boho Waves", label: "Loose Boho Waves" },
  { value: "Retro Finger Waves", label: "Retro Finger Waves" },
  { value: "French Twist", label: "French Twist" },
  { value: "Braided Low Bun", label: "Braided Low Bun" },
  { value: "Dutch Braid into Ponytail", label: "Dutch Braid into Ponytail" },
  { value: "Fishtail Braid", label: "Fishtail Braid" },
  { value: "Crown Braid", label: "Crown Braid" },
  { value: "Twisted Half Updo", label: "Twisted Half Updo" },
  { value: "Classic French Braid", label: "Classic French Braid" },
  { value: "Bubble Ponytail", label: "Bubble Ponytail" },
  { value: "Deep Side Part Straight Hair", label: "Deep Side Part Straight Hair" },
  { value: "Shoulder-Length Curls", label: "Shoulder-Length Curls" },
  { value: "Wispy Curtain Bangs", label: "Wispy Curtain Bangs" },
  { value: "Polished Pixie Cut", label: "Polished Pixie Cut" },
  { value: "Angled Bob", label: "Angled Bob" },
  { value: "Curly Bob", label: "Curly Bob" },
  { value: "Long Glamorous Curls", label: "Long Glamorous Curls" },
  { value: "Straight Long Layers", label: "Straight Long Layers" },
  { value: "Curly Afro", label: "Curly Afro" },
  { value: "Voluminous Natural Curls", label: "Voluminous Natural Curls" },
  { value: "Shoulder-Length Straight Hair", label: "Shoulder-Length Straight Hair" },
  { value: "Pin-Straight Long Hair", label: "Pin-Straight Long Hair" },
  { value: "Micro Bangs with Straight Hair", label: "Micro Bangs with Straight Hair" },
  { value: "Loose Low Chignon", label: "Loose Low Chignon" },
  { value: "Tousled Short Bob", label: "Tousled Short Bob" },
  { value: "Wavy Blunt Cut", label: "Wavy Blunt Cut" },
  { value: "Tight Ringlet Curls", label: "Tight Ringlet Curls" },
  { value: "Layered Long Waves", label: "Layered Long Waves" },
  { value: "Pinned Back Waves", label: "Pinned Back Waves" },
  { value: "Classic Slick Middle Part Bun", label: "Classic Slick Middle Part Bun" },
  { value: "Side Low Ponytail (glam finish)", label: "Side Low Ponytail (glam finish)" },
  { value: "Minimalist Natural Hair Look", label: "Minimalist Natural Hair Look" },
  { value: "Wavy Shag Cut", label: "Wavy Shag Cut" },
];

export const fastGenMaleHairStyle = [
  { value: "Classic Taper", label: "Classic Taper" },
  { value: "Crew Cut", label: "Crew Cut" },
  { value: "Ivy League", label: "Ivy League" },
  { value: "Business Cut", label: "Business Cut" },
  { value: "Short Comb Over", label: "Short Comb Over" },
  { value: "High and Tight Fade", label: "High and Tight Fade" },
  { value: "Textured Crop", label: "Textured Crop" },
  { value: "Side Part Fade", label: "Side Part Fade" },
  { value: "Regulation Cut", label: "Regulation Cut" },
  { value: "Buzz Cut (neat)", label: "Buzz Cut (neat)" },
  { value: "Modern Pompadour", label: "Modern Pompadour" },
  { value: "Soft Side Part", label: "Soft Side Part" },
  { value: "Brushed Back Hair", label: "Brushed Back Hair" },
  { value: "Loose Quiff", label: "Loose Quiff" },
  { value: "Natural Slick Back", label: "Natural Slick Back" },
  { value: "Mid-Length Taper", label: "Mid-Length Taper" },
  { value: "Finger-Combed Texture", label: "Finger-Combed Texture" },
  { value: "Gentle Wave Pushback", label: "Gentle Wave Pushback" },
  { value: "Short Layers", label: "Short Layers" },
  { value: "Layered Crop", label: "Layered Crop" },
  { value: "Grown-Out Ivy League", label: "Grown-Out Ivy League" },
  { value: "Curtain Bangs (middle part, neat)", label: "Curtain Bangs (middle part, neat)" },
  { value: "Soft Bro Flow (polished)", label: "Soft Bro Flow (polished)" },
  { value: "Gentle Curls at Top", label: "Gentle Curls at Top" },
  { value: "Controlled Bedhead Look", label: "Controlled Bedhead Look" },
  { value: "Neat Surfer Hair (not messy)", label: "Neat Surfer Hair (not messy)" },
  { value: "Shoulder-Length Straight Hair (slick)", label: "Shoulder-Length Straight Hair (slick)" },
  { value: "Slightly Wavy Brushed Back", label: "Slightly Wavy Brushed Back" },
  { value: "Natural Parted Waves", label: "Natural Parted Waves" },
  { value: "Mid-Length Swept Back", label: "Mid-Length Swept Back" },
  { value: "Low Taper Fade", label: "Low Taper Fade" },
  { value: "Mid Skin Fade with Short Top", label: "Mid Skin Fade with Short Top" },
  { value: "Temple Fade with Side Part", label: "Temple Fade with Side Part" },
  { value: "Drop Fade with Waves", label: "Drop Fade with Waves" },
  { value: "Light Fade Crew Cut", label: "Light Fade Crew Cut" },
  { value: "Burst Fade with Controlled Volume", label: "Burst Fade with Controlled Volume" },
  { value: "Shadow Fade (soft gradient)", label: "Shadow Fade (soft gradient)" },
  { value: "Bald Fade with Natural Top", label: "Bald Fade with Natural Top" },
  { value: "Scissor Fade (natural looking)", label: "Scissor Fade (natural looking)" },
  { value: "Minimalist Faux Hawk", label: "Minimalist Faux Hawk" },
  { value: "Modern Caesar Cut (light texture)", label: "Modern Caesar Cut (light texture)" },
  { value: "French Crop (soft, no heavy fringe)", label: "French Crop (soft, no heavy fringe)" },
  { value: "Short Afro Fade (tight and clean)", label: "Short Afro Fade (tight and clean)" },
  { value: "Brushed Forward Short Hair", label: "Brushed Forward Short Hair" },
  { value: "Natural Middle Part", label: "Natural Middle Part" },
  { value: "Relaxed Pompadour (light lift)", label: "Relaxed Pompadour (light lift)" },
  { value: "Controlled Fringe", label: "Controlled Fringe" },
  { value: "Soft Textured Spikes", label: "Soft Textured Spikes" },
  { value: "Brushed Down Layers", label: "Brushed Down Layers" },
  { value: "Freshly Trimmed Man Bun (for lifestyle garments)", label: "Freshly Trimmed Man Bun (for lifestyle garments)" },
];
