

import React, { FC, useState } from "react";
import {
	Mail,
	MessageCircle,
	ChevronDown,
	Plus,
	Minus,
	HelpCircle,
	ArrowRight,
} from "lucide-react";

/* --- FAQ ITEM COMPONENT --- */
const FAQItem: FC<{ question: string, answer: string, isOpen: boolean, toggle: () => void }> = ({ question, answer, isOpen, toggle }) => {
	return (
		<div className="border-b border-border last:border-0">
			<button
				onClick={toggle}
				className="w-full flex items-center justify-between py-6 text-left focus:outline-none group"
			>
				<span
					className={`text-lg font-medium transition-colors duration-300 ${isOpen ? "text-brand" : "text-foreground group-hover:text-brand"}`}
				>
					{question}
				</span>
				<div
					className={`relative flex items-center justify-center min-w-8 min-h-8 rounded-full transition-colors duration-300 ${isOpen ? "bg-brand-color text-white" : "bg-secondary text-secondary-foreground group-hover:bg-background"}`}
				>
					{isOpen ? <Minus size={18} /> : <Plus size={18} />}
				</div>
			</button>

			<div
				className={`grid transition-all duration-300 ease-in-out ${isOpen ? "grid-rows-[1fr] opacity-100 pb-6" : "grid-rows-[0fr] opacity-0"}`}
			>
				<div className="overflow-hidden">
					<p className="text-foreground leading-relaxed text-base">{answer}</p>
				</div>
			</div>
		</div>
	);
};

/* --- SUPPORT SECTION --- */
const SupportSection = () => {
	// State to manage which FAQ is open (null = all closed)
	const [openIndex, setOpenIndex] = useState<number | null>(0);

	const faqs = [
		{
			question: "Will the AI-generated models look real?",
			answer:
				"Yes. AI4FI creates 4K photorealistic fashion models with natural skin texture, accurate lighting, realistic body proportions, and authentic fabric draping — optimized for high-conversion e-commerce use.",
		},
		{
			question: "Will my garments fit correctly on different body types?",
			answer:
				"Absolutely. Our system adapts garments to different sizes, including plus-size and diverse body types, ensuring realistic fit, stretch behaviour, folds, and fall — so customers can visualize how the product truly looks.",
		},
		{
			question: "How easy is it to use AI4FI?",
			answer:
				"Very simple. Upload your garment image, choose model attributes (size, pose, ethnicity, styling etc), and generate professional visuals in minutes — no technical skills or design experience required.",
		},
		{
			question: "Is this more affordable than traditional photoshoots?",
			answer:
				"Yes. AI4FI can reduce production costs by up to 90% by eliminating studio rentals, photographers, model hiring, and logistics — while allowing unlimited variations.",
		},
		{
			question: "Can I use these images commercially without legal risks?",
			answer:
				"Yes. All models generated by AI4FI are synthetic and safe for commercial use. There are no real-person likeness issues, making it legally secure for ads, marketplaces, and campaigns."
		}];

	return (
		<section className="relative py-24 px-6 bg-background/80 overflow-hidden">
			{/* Background Decor (Subtle Blur) */}
			<div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-blue-100/40 rounded-full blur-3xl pointer-events-none -z-10"></div>

			<div className="max-w-4xl mx-auto space-y-20">
				{/* --- PART 1: GET IN TOUCH (Redesigned) --- */}
				<div className="text-center space-y-8">
					<div className="space-y-4">
						<h2 className="text-4xl font-extrabold text-foreground">
							Get in Touch
						</h2>
						<p className="text-lg text-secondary-foreground max-w-2xl mx-auto">
							Ready to transform your fashion showcase? Our team is here to help
							you get started with AI-powered fashion photography.
						</p>
					</div>

					{/* Contact Card - Floating Glassmorphism Style */}
					<div className="relative group mx-auto max-w-3xl">
						<div className="absolute -inset-1 bg-gradient-to-r from-blue-400 to-cyan-400 rounded-2xl blur opacity-20 group-hover:opacity-40 transition duration-500"></div>
						<div className="relative bg-secondary rounded-2xl p-8 md:p-10 shadow-xl flex flex-col md:flex-row items-center justify-between gap-8 border border-white/50">
							{/* Left: Icon & Text */}
							<div className="flex items-center gap-6 text-left">
								<div className="w-16 h-16 bg-background text-brand rounded-2xl flex items-center justify-center shadow-inner">
									<Mail size={32} />
								</div>
								<div>
									<h3 className="text-xl font-bold text-foreground">
										Email Support
									</h3>
									<p className="text-slate-500">
										We typically respond within 24 hours.
									</p>
									<a
										href="mailto:support@ai4fi.com"
										className="text-sm font-semibold text-brand mt-1 hover:underline"
									>
										support@ai4fi.com
									</a>
								</div>
							</div>

							{/* Right: Action Button */}
							<button className="flex items-center gap-2 px-8 py-4 bg-brand-color  text-white font-bold rounded-xl shadow-lg shadow-blue-200 transition-transform hover:-translate-y-1 w-full md:w-auto justify-center">
								<MessageCircle size={20} />
								<span>Contact Us</span>
							</button>
						</div>
					</div>
				</div>

				{/* --- PART 2: FAQ (Redesigned) --- */}
				<div className="bg-background  rounded-3xl p-8 md:p-12 shadow-lg border border-border">
					<div className="text-center mb-12">

						<div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-secondary text-muted-foreground text-xs font-bold uppercase tracking-wider mb-4">
							<HelpCircle size={14} /> Help Center
						</div>
						<h2 className="text-3xl font-bold text-foreground">
							Frequently Asked Questions
						</h2>
						<p className="text-slate-500 mt-2">
							Everything you need to know about our AI fashion platform
						</p>
					</div>

					<div className="max-w-3xl mx-auto">
						{faqs.map((faq, index) => (
							<FAQItem
								key={index}
								question={faq.question}
								answer={faq.answer}
								isOpen={openIndex === index}
								toggle={() => setOpenIndex(openIndex === index ? null : index)}
							/>
						))}
					</div>

					<div className="mt-10 text-center">
						<a
							href="#"
							className="inline-flex items-center gap-1 text-sm font-bold text-foreground hover:text-brand transition-colors"
						>
							View all FAQs <ArrowRight size={16} />
						</a>
					</div>
				</div>
			</div>
		</section>
	);
};

export default SupportSection;
